-- changeset zhane:1
create table person_users(
    id int generated by default as identity primary key,
    name varchar(255) not null,
    city varchar(255) not null
);

-- changeset zhane:2
alter table person_users drop column city

